---
title: "Output 3"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(here)
library(janitor)
library(sf)
library(tmap)
library(dplyr)
library(here)
```

```{r}
cities_sf <- read_sf(here("data", "CA_cities_pts2", "CA_cities_pts2.shp")) %>% 
  janitor::clean_names()

comm_df <- read_csv(here("data", "Community_Solar_CA.csv")) %>% 
  janitor::clean_names()

county_sf <- read_sf(here("data", "ca_counties", "CA_Counties_TIGER2016.shp")) %>% 
  janitor::clean_names()
```

```{r}
cities_sf %>% st_crs() #WGS 84 EPSG 4326 
comm_df %>% st_crs()
```

```{r}
city_comm_sf <- full_join(cities_sf, comm_df, by=c("name"="city")) %>% 
  drop_na(project_name)

View(city_comm_sf)
# lost Anza and Herlong, need better city data

city_comm_sf_short <- city_comm_sf %>% 
  select(project_name, name, lat.x, long, county_fips, utility, utility_type, system_size_k_w_ac, system_size_mw_ac, geometry, population.x)

plot(city_comm_sf_short %>% 
       select(system_size_mw_ac)) 

ggplot() + 
  geom_sf(data = county_sf) +
  geom_sf(data = city_comm_sf_short, aes(fill = system_size_mw_ac), size = 2) + # size = border
  scale_fill_gradientn(colors = c('darkorchid4', 'chocolate1')) +
  theme_void() +
  labs(fill = 'System Size (MW-AC)')

# ass3 df for data and df for predictions
# predict(nls_model, newdata=list(doy=seq(147,306)))
```
```{r}
tmap_mode("view") 

tm_shape(county_df) + 
  tm_polygons()+
tm_shape(city_comm_sf_short) +
  tm_dots(size = 0.02) +
tm_view(view.legend.position = c("right", "top"))+
tm_layout(title= 'System Size', 
            title.position = c('right', 'top'))
```

```{r}
ggplot(data = comm_df, aes(x = year_of_interconnection, 
                            y = system_size_mw_ac,
                            color = utility)) +
  geom_col() +
  labs(x = "Year of Interconnection",
       title = "California Community Projects Over Time",
       y = "System Size (kW-AC)", 
       color = "Utility") +
  theme_minimal() +
  scale_x_continuous(breaks = 2011:2021) #show all years

# put system size into perspective with population size? kw/household in city? # households in city?
```


















